#!/bin/sh

# dual monitors
dual &

# startups
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh # dbus
feh --randomize --bg-fill ${HOME}/Pictures/wallpapers/* --no-fehbg &
xautolock -time 10 -locker slock &
redshift &
pipewire >/dev/null 2>&1 &
ibus-daemon -rxR >/dev/null 2>&1 &
picom &
qpwgraph -m &
export $(gnome-keyring-daemon --daemonize --start --components=secrets,ssh)

# WM
exec i3
