#!/bin/sh

# dual monitors
dual &

# input tuning
xinput set-prop Synaptics\ TM3289-021 libinput\ Tapping\ Enabled 1 &
xinput set-prop Synaptics\ TM3289-021 libinput\ Natural\ Scrolling\ Enabled 1 &

# startups
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh # dbus
feh --randomize --bg-fill ${HOME}/Pictures/wallpapers/* --no-fehbg &
dwmblocks &
xautolock -time 10 -locker slock &
redshift &
pipewire >/dev/null 2>&1 &
ibus-daemon -rxR >/dev/null 2>&1 &
picom &
qpwgraph -m &
export $(gnome-keyring-daemon --daemonize --start --components=secrets,ssh)

# WM
exec dwm
