#!/bin/sh

# dual monitors
monitors=$(xrandr --current | grep -w connected | awk '{print $1}')
n=$(echo "$monitors" | wc -l)
if [ $n -eq 2 ]; then
    first=$(echo "$monitors" | head -n 1)
    second=$(echo "$monitors" | tail -n 1)
    xrandr --output "$second" --left-of "$first"
fi

# input tuning
xinput set-prop Synaptics\ TM3289-021 libinput\ Tapping\ Enabled 1 &

# startups
export $(dbus-launch) # dbus must come first
dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY & # for gnome-keyring
feh --randomize --bg-fill ${HOME}/Pictures/wallpapers/* --no-fehbg &
dwmblocks &
xautolock -time 10 -locker slock &
redshift &
pipewire >/dev/null 2>&1 &
ibus-daemon -rxR >/dev/null 2>&1 &
picom &
qpwgraph -m &
export $(gnome-keyring-daemon --start --components=secrets,ssh)

# WM
exec dwm
