#!/bin/sh

# dual monitors
dual &

# input tuning
xinput set-prop Synaptics\ TM3289-021 libinput\ Tapping\ Enabled 1 &

# startups
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh # dbus
feh --randomize --bg-fill ${HOME}/Pictures/wallpapers/* --no-fehbg &
dwmblocks &
xautolock -time 10 -locker slock &
redshift &
pipewire >/dev/null 2>&1 &
qpwgraph -m &

# WM
exec dwm
